# Site settings
title: Design Portfolio
email: ruben.media@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specializing in Jekyll,
  HTML, CSS and Javascript.
baseurl: "designer-portfolio" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: rubenmedios
github_username:  rubenmedios
google_username:  rubenmedios

permalink: /:categories/:title 

links:
  - title: about
    titledesc: pepe es lo mio
    url: /about
  - title: work
    titledesc: pepe es lo mio
    url: /work
  - title: articles
    titledesc: pepe es lo mio
    url: /articles
  - title: hire me
    titledesc: pepe es lo mio
    url: /hire-me

# Build settings
markdown: kramdown
